    #--------------------- DB ----------------------
# DB Connection with the uri (host)
client: "mongodb://mymongo:27017"

# db name
db: "aiot_course"

# db collection
col: "gesture_data"


#--------------------- Dataframe Instantiation ----------------------
# Dataframe columns list
order: ["X", "Y", "Z"]
rename: ["acc_x", "acc_y", "acc_z"]


#--------------------- Dataset Local Storage ----------------------
# dataset location
data_path: "/home/jovyan/work/data/"
# single data instance location path to experiment with the data engineering process and visualization
single_instance_path: "/home/jovyan/work/data/"


#--------------------- Data Engineering ----------------------
# sliding window algorithm parameters
sliding_window:
  ws: 100
  overlap: 25
  w_type: "hann"
  w_center: True
  print_stats: True

# window to handle for visualization purposes
x_number: 2

# filtering parameterization
filter:
  order: 5
  wn: 0.1
  type: "lowpass"


#--------------------- $ Data Preparation ----------------------
# Dimensionality reduction
PCA:
  n_comp: 2


#--------------------- Learning ----------------------
# Classifier - Statistical
classifier:
  SVC:
    C:
    kernel: "rbf"
    gamma:
  # classifier 2
    # put your other Statistical-related classifier params here
  # classifier 3
    # put your other Statistical-related classifier params here

# Parameter Grid for Fine-tuning, for instance, a Grid Search classifier
fine_tune:
  param_grid: [
    {'C': [1, 10, 100, 1000], 'kernel': ['linear']},
    {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf']},
   ]
  cv: 5
  verbose: 1

# Classifier - Neural Network
fit:
  epochs:
  batch:
  verbose: "auto"